import * as xml2js from 'xml2js';
import { UniversalProductData } from '../domain/models';

export class GoogleFeedBuilder {
  static build(data: UniversalProductData): string {
    const items = data.categories.flatMap((category) =>
      category.products.map((product) => {
        const param = product.parameters[0];
        return {
          'g:id': product.id,
          'g:title': product.name,
          'g:description': product.description ?? '',
          'g:link': '',
          'g:image_link': product.image ?? '',
          'g:price': `${param?.price ?? 0} ${param?.priceUnit ?? 'RUB'}`,
          'g:availability': 'in stock',
          'g:google_product_category': category.name,
        };
      })
    );

    const payload = {
      rss: {
        $: {
          version: '2.0',
          'xmlns:g': 'http://base.google.com/ns/1.0',
        },
        channel: {
          title: 'Converted feed',
          link: 'https://example.com',
          description: 'Generated by xml-toolkit',
          item: items,
        },
      },
    };

    const builder = new xml2js.Builder({ headless: false });
    return builder.buildObject(payload);
  }
}
