import * as xml2js from 'xml2js';
import { UniversalProductData } from '../domain/models';

export class GoogleFeedBuilder {
  static build(data: UniversalProductData): string {
    const items = data.categories.flatMap((category) =>
      category.products.map((product) => {
        const param = product.parameters[0];
        return {
          'g:id': product.id,
          'g:title': product.name,
          'g:description': product.description ?? '',
          'g:link': product.link ?? '',
          'g:image_link': product.image ?? '',
          'g:price': '0 RUB',
          'g:availability': 'in_stock',
          'g:product_type': this.buildProductType(category.id, data),
        };
      })
    );

    const payload = {
      rss: {
        $: {
          version: '2.0',
          'xmlns:g': 'http://base.google.com/ns/1.0',
        },
        channel: {
          title: 'Converted feed',
          link: 'https://example.com',
          description: 'Generated by xml-toolkit',
          item: items,
        },
      },
    };

    const builder = new xml2js.Builder({ headless: false });
    return builder.buildObject(payload);
  }
  private static buildProductType(categoryId: string, data: UniversalProductData): string {
    const byId = new Map(data.categories.map((category) => [category.id, category]));
    const parts: string[] = [];

    let current = byId.get(categoryId);
    while (current) {
      parts.unshift(current.name);
      if (!current.parentId) {
        break;
      }
      current = byId.get(current.parentId);
    }

    return parts.join(' > ');
  }

}
