import * as xml2js from 'xml2js';
import { UniversalProductData } from '../domain/models';
import { ColumnType } from '../convert.dto';
import { getXmlFieldConfig } from './xmlFieldConfig';

export class GoogleFeedBuilder {
  static build(data: UniversalProductData): string {
    const productIdCfg = getXmlFieldConfig('google_feed', ColumnType.PRODUCT_ID);
    const productNameCfg = getXmlFieldConfig('google_feed', ColumnType.PRODUCT_NAME);
    const productDescriptionCfg = getXmlFieldConfig('google_feed', ColumnType.PRODUCT_DESCRIPTION);
    const productLinkCfg = getXmlFieldConfig('google_feed', ColumnType.PRODUCT_LINK);
    const productImageCfg = getXmlFieldConfig('google_feed', ColumnType.PRODUCT_IMAGE);
    const productPriceCfg = getXmlFieldConfig('google_feed', ColumnType.PRODUCT_PARAMETER_PRICE);

    const items = data.categories.flatMap((category) =>
      category.products.flatMap((product) => {
        if (!product.parameters.length) {
          return {
            [productIdCfg?.tag ?? 'g:id']: product.id,
            [productNameCfg?.tag ?? 'g:title']: product.name,
            [productDescriptionCfg?.tag ?? 'g:description']: product.description ?? '',
            [productLinkCfg?.tag ?? 'g:link']: product.link ?? '',
            [productImageCfg?.tag ?? 'g:image_link']: product.image ?? '',
            [productPriceCfg?.tag ?? 'g:price']: '0 RUB',
            'g:availability': 'in_stock',
            'g:product_type': this.buildProductType(category.id, data),
          };
        }

        return product.parameters.map((parameter) => ({
          [productIdCfg?.tag ?? 'g:id']: parameter.id || product.id,
          'g:item_group_id': product.id,
          [productNameCfg?.tag ?? 'g:title']: product.name,
          [productDescriptionCfg?.tag ?? 'g:description']: product.description ?? '',
          [productLinkCfg?.tag ?? 'g:link']: product.link ?? '',
          [productImageCfg?.tag ?? 'g:image_link']: product.image ?? '',
          [productPriceCfg?.tag ?? 'g:price']: `${parameter.price ?? 0} RUB`,
          'g:availability': 'in_stock',
          'g:product_type': this.buildProductType(category.id, data),
        }));
      })
    );

    const payload = {
      rss: {
        $: {
          version: '2.0',
          'xmlns:g': 'http://base.google.com/ns/1.0',
        },
        channel: {
          title: 'Converted feed',
          link: 'https://example.com',
          description: 'Generated by xml-toolkit',
          item: items,
        },
      },
    };

    const builder = new xml2js.Builder({ headless: false });
    return builder.buildObject(payload);
  }
  private static buildProductType(categoryId: string, data: UniversalProductData): string {
    const byId = new Map(data.categories.map((category) => [category.id, category]));
    const parts: string[] = [];

    let current = byId.get(categoryId);
    while (current) {
      parts.unshift(current.name);
      if (!current.parentId) {
        break;
      }
      current = byId.get(current.parentId);
    }

    return parts.join(' > ');
  }

}
